[e5e0dc1b-0480-54bc-9374-aad01c23163d]
name = "Juno"
location = "https://docs.junolab.org/latest"
method = "hosted"

[112f6efa-9a02-5b7d-90c0-432ed331239a]
name = "VegaLite"
location = "https://www.queryverse.org/VegaLite.jl/stable/"
method = "hosted"

[91a5bcdd-55d7-5caf-9e0b-520d859cae80]
name = "Plots"
location = "http://docs.juliaplots.org/latest/"
method = "hosted"

[1c8ee90f-4401-5389-894e-7a04a3dc0f4d]
name = "IterableTables"
location = "https://www.queryverse.org/IterableTables.jl/stable/"
method = "hosted"

[1a8c2f83-1ff3-5112-b086-8aa67b057ba1]
name = "Query"
location = "https://www.queryverse.org/Query.jl/stable/"
method = "hosted"

[0c46a032-eb83-5123-abaf-570d42b7fbaa]
name = "DifferentialEquations"
location = "https://github.com/JuliaDiffEq/DiffEqDocs.jl.git"
method = "git-repo"

[c52e3926-4ff0-5f6e-af25-54175e0327b1]
name = "Atom"
location = "https://docs.junolab.org/latest"
method = "hosted"
